import { PageHeader } from '../components/layout/PageHeader'
import { Card, SectionLabel } from '../components/ui/Card'

function Section({ question, children }: { question: string; children: React.ReactNode }) {
  return (
    <div className="space-y-1.5 border-b border-[var(--border)] py-4 last:border-0">
      <h3 className="text-sm font-semibold text-[var(--text-primary)]">{question}</h3>
      <div className="text-sm leading-relaxed text-[var(--text-secondary)]">{children}</div>
    </div>
  )
}

export default function DocumentationPage() {
  return (
    <div className="max-w-3xl space-y-6">
      <PageHeader title="Documentation" description="A concise guide to what TradeLens AI currently does, and doesn't." />

      <Card className="p-5">
        <Section question="What is TradeLens?">
          TradeLens AI is an explainable algorithmic-trading strategy research and auditing platform. It turns
          historical market data into deterministic technical indicators, evaluates a fixed set of strategy
          rules against them, and shows exactly why each decision occurred, with full numeric evidence.
        </Section>

        <Section question="How does the current pipeline work?">
          Historical NSE market data → technical indicators (SMA20, SMA50, Wilder RSI14, rolling volume) →
          the Trend + Momentum v1 strategy rule → an explainable decision with evidence for every historical
          trading date.
        </Section>

        <Section question="What is Trend + Momentum v1?">
          The only strategy currently implemented. It evaluates, independently for each date: whether Close is
          above SMA20, whether SMA20 is above SMA50, and whether RSI14 sits between 40 and 70 inclusive. There
          is no trend-persistence, crossover, or volume filter. Each date is judged on its own.
        </Section>

        <Section question="What does BUY mean?">
          It means all three Trend + Momentum v1 conditions were satisfied for that historical observation.
          It is a description of a deterministic rule outcome, not investment advice, not a recommendation,
          and not a prediction of future performance.
        </Section>

        <Section question="What does NO_SIGNAL mean?">
          At least one of the three conditions failed for that date, with all required indicator values present.
          NO_SIGNAL is not the same as SELL. No SELL logic exists anywhere in TradeLens yet.
        </Section>

        <Section question="What does INSUFFICIENT_DATA mean?">
          One or more indicators required by the strategy (SMA20, SMA50, RSI14, or the underlying Close) had
          not yet warmed up for that date. For example, SMA50 needs 50 prior observations. TradeLens never
          fabricates a decision from incomplete indicator history.
        </Section>

        <Section question="What indicators are currently supported?">
          SMA20, SMA50, Wilder-smoothed RSI14, rolling average volume (20-bar, excluding the current bar), and
          volume ratio (current volume ÷ that rolling average).
        </Section>

        <Section question="What is intentionally not implemented yet?">
          An intelligence/RAG layer, SELL logic, order execution, portfolio or position tracking, and any
          brokerage functionality. These are honestly previewed on their respective pages rather than fabricated.
        </Section>
      </Card>

      <Card className="p-5">
        <Section question="Account &amp; authentication">
          TradeLens accounts exist to keep research sessions private, not to enable trading. You can register
          with an email and password, or continue with Google. Both resolve to the same kind of TradeLens
          account. Your display name and full name can be changed from Settings at any time; your email is
          your verified sign-in identity and isn&apos;t editable from that form. Signing in establishes a
          secure session; signing out ends it immediately.
        </Section>

        <Section question="How research results should be interpreted">
          Every indicator value and strategy decision shown in TradeLens is calculated deterministically from
          historical bars. Nothing is estimated, predicted, or generated by a model. A BUY/NO_SIGNAL/
          INSUFFICIENT_DATA decision describes what the rule found for that specific historical date; it says
          nothing about what will happen next. Treat TradeLens as a lens for understanding historical market
          structure and rule behaviour, not as a source of trading signals to act on.
        </Section>
      </Card>

      <Card className="p-4">
        <SectionLabel>Disclaimer</SectionLabel>
        <p className="mt-1.5 text-xs leading-relaxed text-[var(--text-tertiary)]">
          TradeLens AI is a research and educational project. Nothing in this application constitutes financial,
          investment, or trading advice, and historical strategy behaviour is not a guarantee of future results.
        </p>
      </Card>
    </div>
  )
}
